(()=>{'use strict';
const roundsPerGame=4;
const locations=[
 {name:'TÃ³quio, JapÃ£o',lat:35.6812,lon:139.7671,file:'Tokyo Station - 2022 May 2 - 360 panorama.jpeg'},
 {name:'Nova Iorque, Estados Unidos',lat:40.7571,lon:-73.9859,file:'20080910 Times Square, New York panorama.JPG'},
 {name:'Paris, FranÃ§a',lat:48.8584,lon:2.2945,file:'Paris 360.jpg'},
 {name:'Sydney, AustrÃ¡lia',lat:-33.8705,lon:151.2091,file:'Sydney Tower Panorama.jpg'},
 {name:'Akureyri, IslÃ¢ndia',lat:65.6826,lon:-18.0907,file:'2005-05-26 Akureyri 360.jpg'},
 {name:'Dimmuborgir, IslÃ¢ndia',lat:65.5900,lon:-16.9120,file:'2005-05-28 Dimmuborgir 360.jpg'},
 {name:'Geysir, IslÃ¢ndia',lat:64.3104,lon:-20.3024,file:'2005-05-31 Geysir 02.jpg'},
 {name:'Aqaba, JordÃ¢nia',lat:29.5319,lon:35.0061,file:'2005-08-17 Marina City, Aqaba, Jordanien 01.jpg'},
 {name:'Wadi Rum, JordÃ¢nia',lat:29.5763,lon:35.4213,file:'2005-08-18 Wadi Roum 03, Jordanien.jpg'},
 {name:'Nafpaktos, GrÃ©cia',lat:38.3917,lon:21.8275,file:'2007-05-08 360Â° NÃ¡vpaktos, Greece.jpg'},
 {name:'OlÃ­mpia, GrÃ©cia',lat:37.6386,lon:21.6300,file:'2007-05-09 360Â° Olympia, Greece 3.jpg'},
 {name:'Dubai, Emirados Ãrabes Unidos',lat:25.1952,lon:55.2772,file:'2008-03-20 Old Town, Souk al Bahar 01.jpg'}
];
const $=id=>document.getElementById(id),scene=$('scene'),photo=$('panorama'),copy=$('panoramaCopy');
let map,order=[],locationDeck=[],round=0,score=0,guess,answered=false,results=[],pan=0,dragging=false,startX=0,startPan=0,guessMarker,answerMarker,answerLine,roundToken=0;
const current=()=>locations[order[round]];
const filePage=file=>'https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(file).replace(/%20/g,'_');
const photoUrl=file=>'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent(file);
function haversine(a,b){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlon=(b.lon-a.lon)*r,h=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlon/2)**2;return 6371*2*Math.asin(Math.min(1,Math.sqrt(h)))}
function pickLocations(){if(locationDeck.length<roundsPerGame){locationDeck=[...locations.keys()];for(let i=locationDeck.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[locationDeck[i],locationDeck[j]]=[locationDeck[j],locationDeck[i]]}}return locationDeck.splice(0,roundsPerGame)}
function icon(answer=false){return L.divIcon({className:'',html:'<div class="'+(answer?'answer-pin':'guess-pin')+'"></div>',iconSize:[18,18],iconAnchor:[9,9]})}
function initMap(){map=L.map('mapView',{zoomControl:true,worldCopyJump:true,maxZoom:19}).setView([20,0],2);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'Â© OpenStreetMap',maxZoom:19}).addTo(map);map.on('click',e=>stageGuess(e.latlng.lat,e.latlng.lng));setTimeout(()=>map.invalidateSize(),100)}
function clearMarkers(){for(const layer of [guessMarker,answerMarker,answerLine])if(layer)map.removeLayer(layer);guessMarker=answerMarker=answerLine=null}
function stageGuess(lat,lon){if(answered||!Number.isFinite(lat)||!Number.isFinite(lon))return;guess={lat,lon};if(!guessMarker){guessMarker=L.marker([lat,lon],{icon:icon(),draggable:true,title:'A tua resposta'}).addTo(map);guessMarker.on('dragend',()=>{const p=guessMarker.getLatLng();guess={lat:p.lat,lon:p.lng}})}else guessMarker.setLatLng([lat,lon]);$('confirm').disabled=false;$('mapHint').textContent='Marcador colocado. Aproxima o mapa e arrasta-o para acertar na rua.'}
function setPan(value){const width=photo.getBoundingClientRect().width;if(!width)return;pan=((value%width)+width)%width;photo.style.left=-pan+'px';copy.style.left=(width-pan)+'px'}
function newGame(){order=pickLocations();round=0;score=0;results=[];$('summary').hidden=true;$('score').textContent='0 pontos';renderRound()}
function renderRound(){const token=++roundToken;answered=false;guess=null;pan=0;clearMarkers();$('result').classList.remove('visible');$('confirm').disabled=true;$('confirm').textContent='Confirmar resposta';$('mapHint').textContent='Aproxima o mapa atÃ© Ã  rua e clica onde achas que estÃ¡s.';$('mapTitle').textContent='Escolhe o local no mapa';$('mapPanel').classList.remove('big');$('expand').textContent='â¤¢';const loc=current();$('round').textContent=`Ronda ${round+1} / ${roundsPerGame}`;$('progress').innerHTML=Array.from({length:roundsPerGame},(_,i)=>`<span class="${i<=round?'done':''}"></span>`).join('');map.setView([20,0],2);setTimeout(()=>map.invalidateSize(),20);$('tip').innerHTML='<strong>Onde estÃ¡s?</strong> Roda a fotografia 360Â° e procura a rua no mapa.';$('photoCredit').textContent='Fonte e licenÃ§a desta ronda';$('photoCredit').href=filePage(loc.file);$('loading').style.display='block';$('fail').classList.remove('visible');photo.style.visibility=copy.style.visibility='hidden';photo.onload=()=>{if(token!==roundToken)return;copy.src=photo.src;photo.style.visibility=copy.style.visibility='visible';$('loading').style.display='none';setPan(Math.random()*photo.getBoundingClientRect().width)};photo.onerror=()=>{if(token!==roundToken)return;$('loading').style.display='none';$('fail').classList.add('visible')};photo.src=photoUrl(loc.file)}
$('confirm').addEventListener('click',()=>{if(!guess||answered)return;answered=true;const loc=current(),km=haversine(guess,loc),points=Math.round(5000*Math.exp(-km/1900));score+=points;results.push({name:loc.name,points});$('score').textContent=score.toLocaleString('pt-PT')+' pontos';$('confirm').disabled=true;$('confirm').textContent='Resposta registada';$('mapTitle').textContent='A tua resposta e o local real';$('mapHint').textContent='Amarelo: resposta Â· Verde: local real';guessMarker.dragging.disable();answerMarker=L.marker([loc.lat,loc.lon],{icon:icon(true),title:'Local real'}).addTo(map);answerLine=L.polyline([[guess.lat,guess.lon],[loc.lat,loc.lon]],{color:'#f4b849',weight:3}).addTo(map);$('resultTitle').textContent='Era '+loc.name;$('distance').textContent='Ficaste a '+Math.round(km).toLocaleString('pt-PT')+' km do local.';$('roundPoints').textContent='+'+points.toLocaleString('pt-PT')+' pontos';$('next').textContent=round===roundsPerGame-1?'Ver resultado final':'PrÃ³xima ronda';$('result').classList.add('visible');$('tip').textContent='Local descoberto! Compara os dois marcadores no mapa.';$('mapPanel').classList.add('big');$('expand').textContent='â¤¡';setTimeout(()=>{map.invalidateSize();map.fitBounds(L.latLngBounds([guess.lat,guess.lon],[loc.lat,loc.lon]).pad(.22),{maxZoom:18})},260)});
function next(){if(round<roundsPerGame-1){round++;renderRound();return}$('result').classList.remove('visible');$('mapPanel').classList.remove('big');$('total').textContent=score.toLocaleString('pt-PT');$('roundList').replaceChildren();results.forEach((r,i)=>{const row=document.createElement('div'),label=document.createElement('span'),value=document.createElement('strong');label.textContent=`${i+1}. ${r.name}`;value.textContent=r.points.toLocaleString('pt-PT');row.append(label,value);$('roundList').append(row)});$('summary').hidden=false}
$('next').addEventListener('click',next);$('again').addEventListener('click',newGame);$('reset').addEventListener('click',newGame);$('expand').addEventListener('click',()=>{const big=$('mapPanel').classList.toggle('big');$('expand').textContent=big?'â¤¡':'â¤¢';setTimeout(()=>map.invalidateSize(),260)});
scene.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;startX=e.clientX;startPan=pan;scene.classList.add('dragging');scene.setPointerCapture(e.pointerId)});scene.addEventListener('pointermove',e=>{if(dragging)setPan(startPan+startX-e.clientX)});function stop(){dragging=false;scene.classList.remove('dragging')}scene.addEventListener('pointerup',stop);scene.addEventListener('pointercancel',stop);$('left').addEventListener('click',()=>setPan(pan-scene.clientWidth*.42));$('right').addEventListener('click',()=>setPan(pan+scene.clientWidth*.42));window.addEventListener('resize',()=>{setPan(pan);map.invalidateSize()});window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')setPan(pan-scene.clientWidth*.24);if(e.key==='ArrowRight')setPan(pan+scene.clientWidth*.24)});
if(document.modelContext?.registerTool){const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{})}catch(_){}};register({name:'read_game_state',title:'Ver estado da partida',description:'Consulta a ronda e a pontuaÃ§Ã£o sem revelar o local antes da resposta.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({round:round+1,totalRounds:roundsPerGame,score,answered,place:answered?current().name:null})});register({name:'stage_map_guess',title:'Marcar resposta no mapa',description:'Marca uma latitude e longitude no mapa.',inputSchema:{type:'object',properties:{latitude:{type:'number',minimum:-90,maximum:90},longitude:{type:'number',minimum:-180,maximum:180}},required:['latitude','longitude'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{stageGuess(input.latitude,input.longitude);return {staged:true}}});register({name:'complete_map_guess',title:'Confirmar resposta',description:'Confirma o marcador escolhido.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{if(!guess||answered)throw Error('Coloca primeiro um marcador.');$('confirm').click();return {place:current().name,totalScore:score}}})}
initMap();newGame();
})();
